[dev]
framework = "#custom"
command = "yarn dev"
targetPort = 3000
publish = "dist"

[[redirects]]
from = "/api/*"
to = "https://api.readhub.cn/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
